package xasd

import (
	"github.com/yomoggies/xsapi-go/xal/internal"
)

// Token represents an Xbox Authorization Services for Device (XASD) token.
// It represents a specific device in Xbox Live, and used to either start
// an SISU authorization flow, or used along with the user token to request
// the final XSTS token.
type Token = internal.Token[DisplayClaims]

// DisplayClaims represents the structure of claims issued by XASD, which
// can be found at [Token.DisplayClaims].
type DisplayClaims struct {
	// DeviceInfo contains information about the authenticated device.
	DeviceInfo DeviceInfo `json:"xdi"`
}

// DeviceInfo represents additional information about the device, claimed by XASD.
type DeviceInfo struct {
	// DeviceID is the ID of the device associated by Xbox Live.
	// It is unrelated to the Device ID passed in the request, but uniquely
	// generated by Xbox Live to associate a specific device.
	DeviceID string `json:"did"`
	// DCS is currently unknown.
	DCS string `json:"dcs"`
}
